version: '3.4'

services:
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
  
  catalogdb:
    container_name: catalogdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CatalogConnectionString=Server=catalogdb;Database=Shop.Catalog;User Id=sa;Password=SwN12345678;"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
  
  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnectionString=Server=orderdb;Database=Shop.Ordering;User Id=sa;Password=SwN12345678;"
    depends_on:
      - orderdb
    ports:
      - "8001:80"
