version: '3.4'

services:
  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
   
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/services/Catalog/Api/Catalog.Api/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: src/services/Ordering/Api/Ordering.Api/Dockerfile
