version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      SA_PASSWORD: "SwN12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CatalogConnectionString=Server=catalogdb;Database=Shop.Catalog;User Id=sa;Password=SwN12345678;"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"
