version: '3.4'

services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/services/Catalog/Api/Catalog.Api/Dockerfile
